fix entry which should be an exit, remover tracepoint for async operation computation and comment cleaning in configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,9 +33,9 @@ function is_windows() {
 function bazel_clean_and_fetch() {
   # bazel clean --expunge currently doesn't work on Windows
   # TODO(pcloudy): Re-enable it after bazel clean --expunge is fixed.
-  if ! is_windows; then
-    bazel clean #--expunge
-  fi
+  # if ! is_windows; then
+  #   bazel clean #--expunge
+  # fi
   bazel fetch "//tensorflow/... -//tensorflow/examples/android/..."
 }
 
@@ -618,7 +618,8 @@ if [ "$default_gpu_device" == "AMD" ]; then
       export HCC_HOME
       break
     fi
-    echo "Invalid hcc path. ${HCC_HOME} cannot be found" 1>&2
+    echo "Invalid hcc
+     path. ${HCC_HOME} cannot be found" 1>&2
     if [ -z "$fromuser" ]; then
       exit 1
     fi
